export const ACTIVITIES = [
  {
    id: 'gym',
    title: 'Go to the Gym',
    cost: 50,
    minAge: 13,
    energyCost: 20,
    effects: { health: 2, looks: 1, happiness: 1, stress: -5 },
    text: 'You worked out at the gym.',
    type: 'good',
  },
  {
    id: 'meditate',
    title: 'Meditate',
    cost: 0,
    minAge: 6,
    energyCost: 10,
    effects: { happiness: 3, health: 1, stress: -10 },
    text: 'You meditated and found inner peace.',
    type: 'good',
  },
  {
    id: 'library',
    title: 'Go to Library',
    cost: 0,
    minAge: 6,
    energyCost: 15,
    effects: { smarts: 2, happiness: 1 },
    text: 'You read a book at the library.',
    type: 'good',
  },
  {
    id: 'club',
    title: 'Go Clubbing',
    cost: 100,
    minAge: 18,
    energyCost: 25,
    effects: { happiness: 5, health: -1, stress: -5 },
    text: 'You danced all night at the club!',
    type: 'good',
  },
  {
    id: 'plastic_surgery',
    title: 'Plastic Surgery',
    cost: 5000,
    minAge: 18,
    energyCost: 30,
    risk: 'medium',
    effects: { looks: 20, happiness: 5 },
    text: 'You got a nose job. You look fantastic!',
    type: 'good',
  },
  {
    id: 'find_date',
    title: 'Find a Date',
    cost: 100,
    minAge: 14,
    energyCost: 20,
    effects: { happiness: 2 },
    text: 'You went out looking for love...',
    type: 'neutral',
    isDating: true,
  },
  {
    id: 'commit_crime_burglary',
    title: 'Burgle a House',
    cost: 0,
    minAge: 12,
    energyCost: 25,
    risk: 'high',
    text: 'You are attempting to break into a house...',
    type: 'neutral',
    isCrime: true,
    crimeType: 'burglary',
    effects: { stress: 10, karma: -10 },
  },
  {
    id: 'commit_crime_robbery',
    title: 'Rob a Bank',
    cost: 0,
    minAge: 18,
    energyCost: 30,
    risk: 'extreme',
    text: 'You are attempting to rob a bank! HIGH RISK.',
    type: 'neutral',
    isCrime: true,
    crimeType: 'robbery',
    effects: { stress: 50, karma: -30 },
  },
  {
    id: 'gamble_lottery',
    title: 'Play Lottery',
    cost: 10,
    minAge: 18,
    energyCost: 5,
    risk: 'medium',
    effects: { happiness: 1 },
    text: 'You bought a lottery ticket...',
    type: 'neutral',
    isGambling: true,
  },
  {
    id: 'gamble_horse',
    title: 'Horse Races',
    cost: 100,
    minAge: 18,
    energyCost: 15,
    risk: 'high',
    effects: { happiness: 5, stress: 5 },
    text: "You bet on a horse named 'Lucky Star'...",
    type: 'neutral',
    isGambling: true,
  },
  {
    id: 'adopt_pet_dog',
    title: 'Adopt a Dog',
    cost: 500,
    minAge: 18,
    energyCost: 20,
    effects: { happiness: 20, health: 2, karma: 5, stress: -5 },
    text: 'You adopted a playful puppy!',
    type: 'good',
    isPetAdoption: true,
    petType: 'Dog',
  },
  {
    id: 'adopt_pet_cat',
    title: 'Adopt a Cat',
    cost: 200,
    minAge: 18,
    energyCost: 15,
    effects: { happiness: 15, stress: -5, karma: 5 },
    text: 'You adopted a cute kitten.',
    type: 'good',
    isPetAdoption: true,
    petType: 'Cat',
  },
  {
    id: 'travel_budget',
    title: 'Budget Travel',
    cost: 1000,
    minAge: 18,
    energyCost: 30,
    effects: { happiness: 10, stress: -10 },
    text: 'You went backpacking!',
    type: 'good',
  },
  {
    id: 'travel_luxury',
    title: 'Luxury Cruise',
    cost: 10000,
    minAge: 18,
    energyCost: 25,
    effects: { happiness: 30, stress: -20 },
    text: 'You relaxed on a world cruise.',
    type: 'good',
  },
  {
    id: 'busk',
    title: 'Street Performance (Busk)',
    cost: 0,
    minAge: 12,
    energyCost: 15,
    text: 'You found a spot on the street to perform.',
    type: 'neutral',
    isBusking: true,
  },
  {
    id: 'estate_planning',
    title: 'Estate Planning',
    cost: 0,
    minAge: 18,
    energyCost: 10,
    effects: {},
    text: 'You planned your estate.',
    type: 'neutral',
    isWill: true,
  },
  {
    id: 'pickpocket_activity',
    title: 'Pickpocket',
    cost: 0,
    minAge: 12,
    energyCost: 20,
    risk: 'high',
    effects: {},
    text: 'You try to pick a pocket...',
    type: 'neutral',
    isMinigame: true,
    minigameType: 'pickpocket',
  },
  {
    id: 'court_case_activity',
    title: 'File a Court Case',
    cost: 5000,
    minAge: 18,
    energyCost: 25,
    risk: 'medium',
    effects: { stress: 10 },
    text: 'You decided to take someone to court.',
    type: 'neutral',
    isMinigame: true,
    minigameType: 'court_case',
  },
  {
    id: 'chess_activity',
    title: '♟️ Play Chess',
    cost: 0,
    minAge: 6,
    energyCost: 15,
    effects: { smarts: 1, happiness: 3 },
    text: 'You played a game of chess.',
    type: 'good',
    isMinigame: true,
    minigameType: 'chess',
  },
];
