export const CITIES = [
  {
    id: 'new_york',
    name: 'New York City',
    country: 'United States',
    population: 8336000,
    costIndex: 100,
    crimeRate: 45,
    culture: 90,
    tech: 85,
    nature: 25,
    climate: 'temperate',
  },
  {
    id: 'los_angeles',
    name: 'Los Angeles',
    country: 'United States',
    population: 3898000,
    costIndex: 88,
    crimeRate: 48,
    culture: 85,
    tech: 70,
    nature: 40,
    climate: 'mediterranean',
  },
  {
    id: 'chicago',
    name: 'Chicago',
    country: 'United States',
    population: 2746000,
    costIndex: 72,
    crimeRate: 55,
    culture: 75,
    tech: 65,
    nature: 30,
    climate: 'continental',
  },
  {
    id: 'houston',
    name: 'Houston',
    country: 'United States',
    population: 2304000,
    costIndex: 58,
    crimeRate: 50,
    culture: 60,
    tech: 60,
    nature: 25,
    climate: 'subtropical',
  },
  {
    id: 'miami',
    name: 'Miami',
    country: 'United States',
    population: 442000,
    costIndex: 82,
    crimeRate: 52,
    culture: 70,
    tech: 50,
    nature: 60,
    climate: 'tropical',
  },
  {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    population: 8982000,
    costIndex: 95,
    crimeRate: 40,
    culture: 95,
    tech: 80,
    nature: 30,
    climate: 'maritime',
  },
  {
    id: 'manchester',
    name: 'Manchester',
    country: 'United Kingdom',
    population: 553000,
    costIndex: 60,
    crimeRate: 42,
    culture: 65,
    tech: 55,
    nature: 30,
    climate: 'maritime',
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    population: 2731000,
    costIndex: 72,
    crimeRate: 35,
    culture: 75,
    tech: 75,
    nature: 35,
    climate: 'continental',
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canada',
    population: 631000,
    costIndex: 80,
    crimeRate: 32,
    culture: 70,
    tech: 65,
    nature: 70,
    climate: 'maritime',
  },
  {
    id: 'montreal',
    name: 'Montreal',
    country: 'Canada',
    population: 1705000,
    costIndex: 60,
    crimeRate: 33,
    culture: 80,
    tech: 60,
    nature: 30,
    climate: 'continental',
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    population: 5312000,
    costIndex: 78,
    crimeRate: 30,
    culture: 80,
    tech: 70,
    nature: 70,
    climate: 'subtropical',
  },
  {
    id: 'melbourne',
    name: 'Melbourne',
    country: 'Australia',
    population: 5078000,
    costIndex: 72,
    crimeRate: 28,
    culture: 85,
    tech: 65,
    nature: 55,
    climate: 'temperate',
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    population: 13960000,
    costIndex: 95,
    crimeRate: 15,
    culture: 95,
    tech: 95,
    nature: 20,
    climate: 'humid_subtropical',
  },
  {
    id: 'osaka',
    name: 'Osaka',
    country: 'Japan',
    population: 2691000,
    costIndex: 78,
    crimeRate: 18,
    culture: 70,
    tech: 75,
    nature: 20,
    climate: 'humid_subtropical',
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    population: 2161000,
    costIndex: 90,
    crimeRate: 38,
    culture: 95,
    tech: 65,
    nature: 25,
    climate: 'maritime',
  },
  {
    id: 'lyon',
    name: 'Lyon',
    country: 'France',
    population: 513000,
    costIndex: 65,
    crimeRate: 35,
    culture: 65,
    tech: 55,
    nature: 35,
    climate: 'temperate',
  },
  {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    population: 3645000,
    costIndex: 65,
    crimeRate: 36,
    culture: 85,
    tech: 80,
    nature: 30,
    climate: 'continental',
  },
  {
    id: 'munich',
    name: 'Munich',
    country: 'Germany',
    population: 1472000,
    costIndex: 72,
    crimeRate: 30,
    culture: 70,
    tech: 70,
    nature: 40,
    climate: 'continental',
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    population: 2873000,
    costIndex: 68,
    crimeRate: 42,
    culture: 95,
    tech: 45,
    nature: 25,
    climate: 'mediterranean',
  },
  {
    id: 'milan',
    name: 'Milan',
    country: 'Italy',
    population: 1372000,
    costIndex: 75,
    crimeRate: 38,
    culture: 80,
    tech: 60,
    nature: 20,
    climate: 'mediterranean',
  },
  {
    id: 'madrid',
    name: 'Madrid',
    country: 'Spain',
    population: 3223000,
    costIndex: 60,
    crimeRate: 35,
    culture: 85,
    tech: 55,
    nature: 30,
    climate: 'mediterranean',
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    population: 1620000,
    costIndex: 65,
    crimeRate: 40,
    culture: 80,
    tech: 55,
    nature: 40,
    climate: 'mediterranean',
  },
  {
    id: 'rio_de_janeiro',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    population: 6748000,
    costIndex: 40,
    crimeRate: 68,
    culture: 85,
    tech: 40,
    nature: 65,
    climate: 'tropical',
  },
  {
    id: 'sao_paulo',
    name: 'São Paulo',
    country: 'Brazil',
    population: 12330000,
    costIndex: 42,
    crimeRate: 62,
    culture: 75,
    tech: 55,
    nature: 20,
    climate: 'subtropical',
  },
  {
    id: 'mexico_city',
    name: 'Mexico City',
    country: 'Mexico',
    population: 9200000,
    costIndex: 35,
    crimeRate: 60,
    culture: 80,
    tech: 45,
    nature: 25,
    climate: 'subtropical',
  },
  {
    id: 'beijing',
    name: 'Beijing',
    country: 'China',
    population: 21540000,
    costIndex: 55,
    crimeRate: 22,
    culture: 90,
    tech: 80,
    nature: 20,
    climate: 'continental',
  },
  {
    id: 'shanghai',
    name: 'Shanghai',
    country: 'China',
    population: 24870000,
    costIndex: 62,
    crimeRate: 20,
    culture: 80,
    tech: 85,
    nature: 15,
    climate: 'humid_subtropical',
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    country: 'India',
    population: 12480000,
    costIndex: 30,
    crimeRate: 45,
    culture: 75,
    tech: 55,
    nature: 20,
    climate: 'tropical',
  },
  {
    id: 'delhi',
    name: 'Delhi',
    country: 'India',
    population: 16780000,
    costIndex: 28,
    crimeRate: 48,
    culture: 70,
    tech: 50,
    nature: 15,
    climate: 'arid',
  },
  {
    id: 'moscow',
    name: 'Moscow',
    country: 'Russia',
    population: 12500000,
    costIndex: 50,
    crimeRate: 44,
    culture: 80,
    tech: 55,
    nature: 25,
    climate: 'continental',
  },
  {
    id: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    population: 9776000,
    costIndex: 70,
    crimeRate: 16,
    culture: 85,
    tech: 95,
    nature: 20,
    climate: 'continental',
  },
  {
    id: 'dubai',
    name: 'Dubai',
    country: 'United Arab Emirates',
    population: 3331000,
    costIndex: 85,
    crimeRate: 8,
    culture: 50,
    tech: 75,
    nature: 10,
    climate: 'arid',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    population: 5686000,
    costIndex: 88,
    crimeRate: 10,
    culture: 70,
    tech: 90,
    nature: 25,
    climate: 'tropical',
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    population: 872000,
    costIndex: 78,
    crimeRate: 28,
    culture: 80,
    tech: 70,
    nature: 30,
    climate: 'maritime',
  },
  {
    id: 'stockholm',
    name: 'Stockholm',
    country: 'Sweden',
    population: 975000,
    costIndex: 82,
    crimeRate: 22,
    culture: 75,
    tech: 75,
    nature: 50,
    climate: 'continental',
  },
  {
    id: 'zurich',
    name: 'Zurich',
    country: 'Switzerland',
    population: 415000,
    costIndex: 110,
    crimeRate: 12,
    culture: 65,
    tech: 70,
    nature: 50,
    climate: 'temperate',
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    population: 15460000,
    costIndex: 35,
    crimeRate: 50,
    culture: 85,
    tech: 45,
    nature: 20,
    climate: 'mediterranean',
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    population: 10539000,
    costIndex: 25,
    crimeRate: 42,
    culture: 75,
    tech: 50,
    nature: 25,
    climate: 'tropical',
  },
  {
    id: 'nairobi',
    name: 'Nairobi',
    country: 'Kenya',
    population: 4397000,
    costIndex: 22,
    crimeRate: 55,
    culture: 60,
    tech: 40,
    nature: 35,
    climate: 'subtropical',
  },
  {
    id: 'cape_town',
    name: 'Cape Town',
    country: 'South Africa',
    population: 4330000,
    costIndex: 35,
    crimeRate: 62,
    culture: 70,
    tech: 45,
    nature: 70,
    climate: 'mediterranean',
  },
];

export function getCitiesByCountry(countryName) {
  return CITIES.filter(c => c.country === countryName);
}

export function getCity(id) {
  return CITIES.find(c => c.id === id);
}

export function getCityByName(name) {
  return CITIES.find(c => c.name === name);
}

export function getDefaultCityForCountry(countryName) {
  const cities = getCitiesByCountry(countryName);
  return cities.length > 0 ? cities[0] : null;
}
